name: AnimTools
depend: [Libraries, Multiverse-Core]
version: 1.0
main: fr.entasia.animtools.Main
commands:
  anim:
    aliases: [anim, anims, animtool, animtools]

  menuanim:
    aliases: [animmenu]