name: AnimTools
depend: [Libraries, Multiverse-Core]
author: iTrooz_, Narcos
api-version: '1.15'
version: '-1'
main: fr.entasia.animtools.Main
commands:
  anim:
    aliases: [anim, anims, animtool, animtools]

  menuanim:
    aliases: [animmenu]